version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  civo-filter-tweet:
    lang: go
    handler: ./filter-tweet
    image: alexellis2/civo-filter-tweet:0.2.0
    secrets:
    - civo-slack-incoming-webhook-url
    environment:
      username: "CivoCloud"
      read_debug: "true"
      write_debug: "true"
    labels:
      com.openfaas.scale.zero: false
